#define Py_mp_ass_subscript 1
#define Py_mp_length 2
#define Py_mp_subscript 3
#define Py_nb_absolute 4
#define Py_nb_add 5
#define Py_nb_and 6
#define Py_nb_bool 7
#define Py_nb_divmod 8
#define Py_nb_float 9
#define Py_nb_floor_divide 10
#define Py_nb_index 11
#define Py_nb_int 12
#define Py_nb_invert 13
#define Py_nb_lshift 14
#define Py_nb_multiply 15
#define Py_nb_negative 16
#define Py_nb_or 17
#define Py_nb_positive 18
#define Py_nb_power 19
#define Py_nb_remainder 20
#define Py_nb_rshift 21
#define Py_nb_subtract 22
#define Py_nb_true_divide 23
#define Py_nb_xor 24
#define Py_sq_ass_item 25
#define Py_sq_concat 26
#define Py_sq_contains 27
#define Py_sq_item 28
#define Py_sq_length 29
#define Py_sq_repeat 30
#define Py_tp_alloc 31
#define Py_tp_base 32
#define Py_tp_bases 33
#define Py_tp_call 34
#define Py_tp_clear 35
#define Py_tp_dealloc 36
#define Py_tp_del 37
#define Py_tp_descr_get 38
#define Py_tp_descr_set 39
#define Py_tp_doc 40
#define Py_tp_getattr 41
#define Py_tp_getattro 42
#define Py_tp_hash 43
#define Py_tp_init 44
#define Py_tp_iter 45
#define Py_tp_iternext 46
#define Py_tp_methods 47
#define Py_tp_new 48
#define Py_tp_repr 49
#define Py_tp_richcompare 50
#define Py_tp_setattr 51
#define Py_tp_setattro 52
#define Py_tp_str 53
#define Py_tp_members 54
#define Py_tp_getset 55
#define Py_tp_free 56
#define Py_nb_matrix_multiply 57
#define Py_tp_finalize 58
